name: luhouyang_portfolio
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dynamic_color: ^1.5.4
  firebase_core: ^2.24.2
  scroll_to_index: ^3.0.1
  url_launcher: ^6.1.5 #URLauncher
  http: ^1.0.0 #httpclient
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/svg/
    - assets/pics/SD_Blue.png

  fonts:
  - family: GoogleSans
    fonts:
    - asset: assets/fonts/google_sans_regular.ttf
    - asset: assets/fonts/google_sans_italic.ttf
      style: italic
