// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ_mDLz1feIGPE3RUV8TOk7UtVSEWccos',
    appId: '1:988510991988:web:42c0f8ca5a922233b44321',
    messagingSenderId: '988510991988',
    projectId: 'luhouyang-portfolio',
    authDomain: 'luhouyang-portfolio.firebaseapp.com',
    storageBucket: 'luhouyang-portfolio.appspot.com',
    measurementId: 'G-FWYMSWMB82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5rJ-UnlSvllzEfojq6Viojn4okfdkftg',
    appId: '1:988510991988:android:8d29d819601000cfb44321',
    messagingSenderId: '988510991988',
    projectId: 'luhouyang-portfolio',
    storageBucket: 'luhouyang-portfolio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoXkkYSj2kEUuKosVEUKPfrSV2h7ZYOjU',
    appId: '1:988510991988:ios:2916f7b766fef91db44321',
    messagingSenderId: '988510991988',
    projectId: 'luhouyang-portfolio',
    storageBucket: 'luhouyang-portfolio.appspot.com',
    iosBundleId: 'com.example.luhouyangPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoXkkYSj2kEUuKosVEUKPfrSV2h7ZYOjU',
    appId: '1:988510991988:ios:9b8637276cf8200eb44321',
    messagingSenderId: '988510991988',
    projectId: 'luhouyang-portfolio',
    storageBucket: 'luhouyang-portfolio.appspot.com',
    iosBundleId: 'com.example.luhouyangPortfolio.RunnerTests',
  );
}
